### ISSUE TITLE
Memory Leak? With <vec>.set_len

### ISSUE THREAD

**Issue by errantmind** [magiclen/trim-in-place#1]
Hello, the code for `trim_in_place(..)` uses set_len(..) which appears to resize the vector / String. Are you sure this doesn't leak memory?

**Comment by magiclen** [comment]
`String` uses a `Vec` of `u8`s. Does a `u8` value need to be freed? No, because `u8` is a primitive data type.

**Comment by errantmind** [comment]
Makes sense, thanks for the explanation
